const netlife = require('../../lib/index');

describe('SMS API', () => {
  it('Authenticate', () => {
    netlife.sms.auth({
      apiKey: process.env.SMS_BDN_KEY,
      apiAccount: process.env.SMS_BDN_ACCOUNT
    });
  });

  // it('Send single SMS', () => {
  //   netlife.sms.sendSingle({
  //     recipient: '+4795033467',
  //     from: 'Netlife',
  //     message: 'This is a test generated by Mocha.',
  //   }, (err) => {
  //     if (err) {
  //       throw new Error(err);
  //     }
  //
  //     // => All done
  //   });
  // });
});
